# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MJCDistance__ <- function(X, Y, beta) {
    .Call(`_TSDistExtra_MJCDistance__`, X, Y, beta)
}

TWEDistance__ <- function(X, Xts, Y, Yts, nu, lambda, degree) {
    .Call(`_TSDistExtra_TWEDistance__`, X, Xts, Y, Yts, nu, lambda, degree)
}

PrunedDTWDistance__ <- function(X, Y, w) {
    .Call(`_TSDistExtra_PrunedDTWDistance__`, X, Y, w)
}

