# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MJCDistance <- function(X, Y, beta) {
    .Call('_TSDistExtra_MJCDistance', PACKAGE = 'TSDistExtra', X, Y, beta)
}

TWEDistance <- function(X, Xts, Y, Yts, nu, lambda, degree) {
    .Call('_TSDistExtra_TWEDistance', PACKAGE = 'TSDistExtra', X, Xts, Y, Yts, nu, lambda, degree)
}

